# override file for local development
version: '3'
services:
  api:
    ports:
      - 4000:4000
      - 9229:9229
    environment:
      - PORT=4000
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
      - ./yarn.lock:/usr/src/app/yarn.lock
      - ./node_modules:/usr/src/app/node_modules
    command: yarn start:debug

  commands:
    environment:
      - NODE_ENV=development
    volumes:
      - .:/usr/src/app
      - ./yarn.lock:/usr/src/app/yarn.lock
      - ./node_modules:/usr/src/app/node_modules
    command: yarn start:commands:dev

  redis:
    ports:
      - 6379:6379

  db:
    ports:
      - 5432:5432

  # веб-интерфейс логов
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080
