version: '3'

services:
  api:
    image: registry.gitlab.com/andrey_inihov/corporate-portal
    ports:
      - 80:80
    environment:
      - PORT=80
      - NODE_ENV=testing # test зарезервировано для jest
      - DATABASE_URL=postgres://postgres:developer@db:5432/corporate_portal
      - REDIS_URL=redis://redis:6379/0
      - SESSION_SECRET=7d58b345d95b5b021dc16fd5b48a8f8b
      - API_VERSION=1.0
      - JWT_SECRET=jwtsecret
      - UNIQUE_NAME_PG_DB=corporate_portal
      - UNIQUE_NAME_PG_TEST_DB=corporate_portal_test
      - UNIQUE_NAME_PG_PORT=5432
      - UNIQUE_NAME_PG_HOST=db
      - UNIQUE_NAME_PG_USER=postgres
      - UNIQUE_NAME_PG_PASSWD=developer

    depends_on:
      - db
      - redis
    command: yarn start

  db:
    image: postgres
    tmpfs:
      - /tmp
      - /var/run/postgresql
    volumes:
      -  db:/var/lib/postgresql/data
      - ./postgres-initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=developer
    ports:
      - 5432:5432

  redis:
    image: redis:latest
    read_only: true
    volumes:
      - redis:/data
    user: redis

volumes:
  db:
  redis:
